### ISSUE TITLE
Change FHIR Server Auditing

### ISSUE THREAD

**Issue by emuhell** [oliver-krauss/ProcessMiningOnFHIR#14]
After a review with @oliver-krauss and @pointan we came to the conclusion that we need some minor changes to the way the AuditEvents are logged. 

1. basedOn should reference an Encounter resource - that one should be specific for each process instance, i.e., for each patient. So we must create a new Encounter resource at the beginning of one process execution and then reference it in every AuditEvent.
2. we should remove the patient from AuditEvent/agent. @oliver-krauss points out that we were actually using it wrong.

**Comment by pointan** [comment]
Hmm it seems, that the Pull request didn't close this ticket, therefore closing it manually.
