### ISSUE TITLE
Extensions and Details

### ISSUE THREAD

**Issue by alackerbauer** [oliver-krauss/ProcessMiningOnFHIR#19]
* add a second basedOn extension, referencing the initially created PlanDefinition
* rename FullURL detail to RequestedURL
* change basedOn URL to https://fhirserver.com/extensions/auditevent-basedon

**Comment by alackerbauer** [comment]
@oliver-krauss Emmanuel and I decided on some quite last-minute changes about the basedOn Extension that also affects your XESProvider. We now have 2 basedOn Extensions, one with PlanDefinition and one with Encounter as a value. Plus we changed to URL of the extension.

Here is a small example of how it should look now with these changes:


```
{
  "resourceType": "AuditEvent",
  "extension": [
    {
      "url": "https://fhirserver.com/extensions/auditevent-basedon",
      "valueReference": {
        "reference": "Encounter/[encounterId]"
      }
    },
    {
      "url": "https://fhirserver.com/extensions/auditevent-basedon",
      "valueReference": {
        "reference": "PlanDefinition/RadiologyWorkflow"
      }
    }
  ],
  "action": "C",
  "recorded": "2020-08-14T08:42:51.523+02:00",
  "entity": [
    {
      "what": {
        "type": "DiagnosticReport"
      },
      "detail": [
        {
          "type": "FullURL",
          "valueString": "[fhirserver]/DiagnosticReport/"
        }
      ]
    }
  ]
}
```

Can you please apply these changes to the XESProvider?

**Comment by oliver-krauss** [comment]
Could we first talk about the reasoning behind duplicating "https://fhirserver.com/extensions/auditevent-basedon" for two very distinct purposes? Encounter (in what context it happened) PlanDefinition (what process definition this process was based on).

You might have reasons to duplicate that I don't understand, but at first glance this should be two distinct Extensions.

**Comment by alackerbauer** [comment]
hello oliver! 

i haven't really thought too much about the purposes but Emmanuel's wish to have it look like the basedOn Element is already part of AuditEvent (instead of an extension for now), which would allow for multiple referenced values (0..*). therefore he suggested using the same extension URL for both things. 

would you agree with having both of these things (PlanDefinition and Encounter) referenced by the basedOn element if it was already there in the AuditEvent? 

after looking at other resources again, maybe this statement that it would be represented both as basedOn is not entirely true, see https://www.hl7.org/fhir/procedure.html where basedOn only refers to a ServiceRequest or a CarePlan and encounter is its very own element...

@emuhell what do you think?

also, for @oliver-krauss you can read the brief "discussion" that emmanuel and I had on monday evening in the teams chat "Process Mining on FHIR Paper" Monday, 21:17-21:33

in general, any change there is very easy to implement on the server state so i am fine with anything that makes sense :)

**Comment by oliver-krauss** [comment]
AuditEvent (https://www.hl7.org/fhir/auditevent.html, http://build.fhir.org/auditevent.html) does not currently have a based on but it is under discussion in https://jira.hl7.org/browse/FHIR-28100. This would consider a field for Encounter and a separate field for PlanDefinition.

After discussion with Andreas I'd suggest creating a separate extension for the PlanDefinition. if I interpret 28100 correctly Encounter will be represented by the field "encounter" and PlanDefinition by the field "based-on", which is what we could use for our Extension URLs. 

PS.: based-on may very well become a new extension and not a new field

**Comment by alackerbauer** [comment]
i applied the changes to the AuditEvent generation accordingly (see last commit). once changed in the XES generation code, i can open a pull request.

**Comment by pointan** [comment]
Hmm the corresponding Pull request was already merged, but it didn't close this ticket, so doing it manually.
