### ISSUE TITLE
Add XES Operation to FHIR Server

### ISSUE THREAD

**Issue by oliver-krauss** [oliver-krauss/ProcessMiningOnFHIR#6]
Add a FHIR XES Operation that lets you retrieve an audit log as XES file

**Comment by oliver-krauss** [comment]
Blocked until @emuhell provides Mapping from AuditEvent to XES

**Comment by alackerbauer** [comment]
so sorry for the commit issue number collision, i was actually working with GitLab issues the whole time. didn't know we would do issue tracking in GitHub for this project (makes sense though ;) )

**Comment by pointan** [comment]
> 
> 
> so sorry for the commit issue number collision, i was actually working with GitLab issues the whole time. didn't know we would do issue tracking in GitHub for this project (makes sense though ;) )

Good point, maybe if I find some time in the next few days, I will create the issues from gitlab in github here, and change the commit messages to the corresponding onces here.

**Comment by pointan** [comment]
> Good point, maybe if I find some time in the next few days, I will create the issues from gitlab in github here, and change the commit messages to the corresponding onces here.

Done.
